import React, { PropsWithChildren } from 'react';
import { notFound } from 'next/navigation';
import { Inter } from 'next/font/google';

import { LOCALES } from '@/constants/i18n';
import { Locale } from '@/types/i18n';

import '@/styles/globals.css';

import { Nav } from './nav';
import { Footer } from './footer';

const inter = Inter({
  variable: '--font-sans',
  display: 'swap',
  subsets: ['latin', 'latin-ext', 'cyrillic-ext'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(props: PropsWithChildren & { params: { locale: Locale } }) {
  if (!LOCALES.includes(props.params.locale as Locale)) notFound();

  return (
    <html className={[inter.variable, 'font-sans'].join(' ')} lang={props.params.locale}>
      <body>
        {/* @ts-expect-error Server component */}
        <Nav locale={props.params.locale} />
        <main id="content" className="flex flex-col items-center flex-1">
          <div className="flex-1 cib-section w-full py">
            <div className="flex-1 mb-4" />
            {props.children}
            <div className="flex-1 mb-4" />
            <div className="flex-1 mb-4" />
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
